# This is a basic workflow to help you get started with Actions

name: Deploy to Prod

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: 18.168.179.48
          key: ${{ secrets.DEPLOY_KEY }}
          username: ubuntu
          script: cd ~/repos/united-tickets-monitoring;git fetch --all; git reset --hard origin/master; source ./united-tickets-monitoring-venv/bin/activate; pip install -r ./requirements.txt; deactivate; ps -ef | grep 'poller.py' | grep -v grep | awk '{print $2}' | xargs -r kill -9; ps -ef | grep 'database_watcher.py' | grep -v grep | awk '{print $2}' | xargs -r kill -9; ./run.sh 
